### ISSUE TITLE
can't stop project

### ISSUE THREAD

**Issue by icsabai** [kooplex/kooplex-hub#17]
I have forked a public project (elte:  pallag/methylation), started it and cannot stop. For some reason the system thinks I want to delete, not stop.
This is the Stop button URL: 
https://compare.vo.elte.hu/hub/notebooks/delete?notebook_id=aa776da9-e91f-47ff-b2ed-2ac79dcbc077&session_id=2e316a92-6182-428d-9f70-765d16a95586

And this is the error message:

APIError at /hub/notebooks/delete
409 Client Error: Conflict ("b'{"message":"You cannot remove a running container e648472602f12b1fc89e78863ff6ae7187daedc8e48a717ccde70ce98d1fdfd3. Stop the container before attempting removal or use -f"}'")
Request Method:	GET
Request URL:	http://kooplex1/hub/notebooks/delete?notebook_id=aa776da9-e91f-47ff-b2ed-2ac79dcbc077&session_id=2e316a92-6182-428d-9f70-765d16a95586
Django Version:	1.9
Exception Type:	APIError
Exception Value:	
409 Client Error: Conflict ("b'{"message":"You cannot remove a running container e648472602f12b1fc89e78863ff6ae7187daedc8e48a717ccde70ce98d1fdfd3. Stop the container before attempting removal or use -f"}'")
Exception Location:	/usr/local/lib/python3.5/dist-packages/docker/client.py in _raise_for_status, line 174
Python Executable:	/usr/bin/python3
Python Version:	3.5.2
Python Path:	
['/usr/local/lib/python3.5/dist-packages/git/ext/gitdb',
 '/kooplexhub/kooplexhub',
 '/usr/lib/python35.zip',
 '/usr/lib/python3.5',
 '/usr/lib/python3.5/plat-x86_64-linux-gnu',
 '/usr/lib/python3.5/lib-dynload',
 '/usr/local/lib/python3.5/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/usr/local/lib/python3.5/dist-packages/gitdb/ext/smmap']
Server time:	Tue, 6 Jun 2017 14:58:21 -0500

**Comment by icsabai** [comment]
At the same time, other user (Pollner P.) of the same project cannot commit. Error:

RestClientError at /hub/notebooks/open

**Comment by stegerjozsef** [comment]
I cannot reproduce this issue in the new installation. Please close.
