### ISSUE TITLE
password change w confimation/ passwd reset

### ISSUE THREAD

**Issue by riblidezso** [kooplex/kooplex-hub#18]
1, Jo lenne ha 2x kene beutni az uj jelszot, jelszo valtasnal. Ez mindenhol igy szokott lenni, hogy megelozd a hibat.

2, Ha mar van password change, akkor kellene hogy legyen password reset is, ne kelljen minden alkalommal az adminokkal emailezgetni ha elfelejti valaki a jelszot.

**Comment by stegerjozsef** [comment]
Köszi. 

Az 1. pont elkészült. 
A 2.-ra most csak admin jogosult, igyekszem kiterjeszteni.

**Comment by stegerjozsef** [comment]
a 2-esre is született egy megoldás
