### ISSUE TITLE
safari: "Connecting to kernel"

### ISSUE THREAD

**Issue by riblidezso** [kooplex/kooplex-hub#19]
Safarival nem tudok notebookozni. Azt mondja hogy connecting to kernel naracssargan azt ennyi. Firefox-al megy. 

Ha jol tudom ez a self-signed ervenytelen tanusitvany miatt van.
https://github.com/jupyter/notebook/issues/1744
" Safari does not allow websocket connections on https if the certificate is 'untrusted' "

Ha csak valahogy ervenyesititek akkor megoldodik.

Nem erdemes elhanyagolni, mert csak a mac-ek baja, mert szerintem rengeteg compare partner macezik.

Kosz 
Dezso

**Comment by stegerjozsef** [comment]
Az SSL tanúsítványt bekértem, és telepítettem. Légyszi teszteld, és ha műxik zárd le.

**Comment by riblidezso** [comment]
Koszi, mukodik
