### ISSUE TITLE
no such user

### ISSUE THREAD

**Issue by sotiattila** [kooplex/kooplex-hub#30]
Can not sart shared project.

Environment:

Request Method: GET
Request URL: http://kooplex3/hub/notebooksstart_container?project_id=87

Django Version: 1.9
Python Version: 3.5.2
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'kooplex.hub.apps.HubConfig',
 'kooplex.hub.templatetags',
 'django.contrib.admin',
 'django.contrib.admindocs')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'threadlocals.middleware.ThreadLocalMiddleware')

Traceback:

File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/kooplexhub/kooplexhub/kooplex/hub/views/notebooks.py" in container_start
  239.     notebook = spawner.ensure_notebook_running()

File "/kooplexhub/kooplexhub/kooplex/lib/spawner.py" in ensure_notebook_running
  258.             notebook = self.make_notebook()

File "/kooplexhub/kooplexhub/kooplex/lib/spawner.py" in make_notebook
  192.         U = ldp.get_user(self.username) 

File "/kooplexhub/kooplexhub/kooplex/lib/ldap.py" in get_user
  178.             raise LdapException('no such user')

Exception Type: LdapException at /hub/notebooksstart_container
Exception Value: no such user

**Comment by jegesm** [comment]
Hello,

a masik email cimeddel regisztraltunk, azzal probalj meg belepni.

Udv,
David

**Comment by jegesm** [comment]
Vagyis ezt inkabb ne ide ird be  :)
