### ISSUE TITLE
typo in assingment window

### ISSUE THREAD

**Issue by ferdinandyb** [kooplex/kooplex-hub#35]
on kooplex-edu there's a typo when you go into the assignment pane

![image](https://user-images.githubusercontent.com/6343487/46962976-cbf75c80-d0a4-11e8-8f5b-3b3797ade885.png)

It should say `assign`.

**Comment by oroszl** [comment]
yep 
right now it means "seggelés"  in Hungarian. Which of course has also some truth content to it.. :P

**Comment by jegesm** [comment]
Done
