### ISSUE TITLE
be able to combine several courses into one kooplex teaching project

### ISSUE THREAD

**Issue by ferdinandyb** [kooplex/kooplex-hub#37]
Feature request for kooplex-edu:

A course might run under several codes, and it would be great to be able to handle them in once instance. E.g. for canvas.elte.hu, you can (in neptun) define which courses should get one instance of the canvas e-learning course which makes handling multiple classes easy.

Additional super option would be to somehow manually add people to the course (e.g. PhD student want to attend but can't or doesn't want to actually take the course officially).

**Comment by jegesm** [comment]
- Multiple coursecodes can now be mapped to the same course.

- Additional students can be added by administrators easily, just ask
