### ISSUE TITLE
siesta-qe image problem

### ISSUE THREAD

**Issue by Kolja76** [kooplex/kooplex-hub#41]
This image does not contain a full linux installation, important base programs are missing, which can come handy when scripting: eg.: bc, colrm, man

Is it possible to add these?

**Comment by jegesm** [comment]
installed *bc* and *bsdmainutils*. Though not sure how to install the manpages. The *manpages* package is also installed, but there are still no manual for the commands.

You need to stop, delete and start again your container.

**Comment by jegesm** [comment]
installed *bc* and *bsdmainutils*. Though not sure how to install the manpages. The *manpages* package is also installed, but there are still no manual for the commands.

You need to stop, delete and start again your container.
